Web binding
Picovoice/koala pull request #5
Opened 2023-02-09 19:16 UTC by ksyeo1010

- add koala web binding
- add cypress unit + perf test
- add web workflow

2023-02-10 23:21 UTC, ErisMik approved these changes

2023-02-10 23:21 UTC, ErisMik commented on binding/web/src/koala.ts
> +  public static async _init(
Should be `private` right, or I feel like I remember we had to do this on purpose because we use it somewhere else right?

2023-02-11 00:01 UTC, ksyeo1010 commented on binding/web/src/koala.ts
> +  public static async _init(
its for `KoalaWorker` as well.

2023-02-11 00:50 UTC, laves requested changes

2023-02-11 00:50 UTC, laves commented on .github/workflows/web-codestyle.yml
> +    branches: [ main ]
```suggestion
    branches: [ main, 'v[0-9]+.[0-9]+' ]
```

2023-02-11 00:50 UTC, laves commented on .github/workflows/web-perf.yml
> +    branches: [ main ]
Needed for releases
```suggestion
    branches: [ main, 'v[0-9]+.[0-9]+' ]
```

2023-02-11 00:50 UTC, laves commented on .github/workflows/web-perf.yml
> +      - 'binding/web/test/koala_perf.test.ts'
`resources/audio_samples/**` too (incase our test audio changes)

2023-02-11 00:50 UTC, laves commented on .github/workflows/web-perf.yml
> +      - 'binding/web/test/koala_perf.test.ts'
`resources/audio_samples/**`

2023-02-11 00:50 UTC, laves commented on .github/workflows/web-perf.yml
> +            procPerformanceThresholdSec: 1.2
do we need python?

2023-02-11 00:50 UTC, laves commented on .github/workflows/web.yml
> +        python-version: [3.8]
are we using this?

2023-02-11 00:50 UTC, laves commented on README.md
> +        - [Web](#web)
looks like you removed the link to the C section?

2023-02-11 00:50 UTC, laves commented on README.md
> +}
be more clear to call it "AudioFrame"
```suggestion
function getAudioFrame(): Int16Array {
  // ... function to get a frame of audio
}
```

2023-02-11 00:50 UTC, laves commented on README.md
> +    await koala.process(getAudioData());
```suggestion
    await koala.process(getAudioFrame());
```

2023-02-11 00:50 UTC, laves commented on binding/web/README.md
> +## Koala Speech-to-Text Engine
```suggestion
## Koala Noise Suppression Engine
```

2023-02-11 00:50 UTC, laves commented on binding/web/README.md
> +```
I think you should just merge the contents of this section into the one below. There are a bit too many sections in this README

2023-02-11 00:50 UTC, laves commented on binding/web/src/koala_worker.ts
> +            resolve(new KoalaWorker(worker, event.data.version, event.data.frameLength, event.data.sampleRate, event.data.delaySample));
can you spread the args to their own lines to make diffs easier?

2023-02-11 00:50 UTC, laves commented on binding/web/src/koala_worker.ts
> +   * The transcript result will be supplied with the callback provided when initializing the worker either
no transcript from Koala

2023-02-13 17:52 UTC, laves approved these changes

2023-02-13 17:53 UTC, laves commented
go ahead and release pkgs

2023-02-13 18:51 UTC, merged