v1.0 android
Picovoice/koala pull request #8
Opened 2023-02-10 22:16 UTC by ErisMik

2023-02-13 21:39 UTC, ksyeo1010 requested changes

2023-02-13 21:39 UTC, ksyeo1010 commented on binding/android/README.md
> +1. Either create a model in [Picovoice Console](https://console.picovoice.ai/) or use the [default model](../../lib/common).
can't create models

2023-02-13 21:39 UTC, ksyeo1010 commented on binding/android/build.gradle
> +        classpath "com.github.dcendents:android-maven-gradle-plugin:2.1"
this is not required now: take a look at this PR https://github.com/Picovoice/cobra/pull/133

2023-02-13 21:39 UTC, ksyeo1010 commented on binding/android/koala/src/main/java/ai/picovoice/koala/Koala.java
> +         * Setter the AccessKey
```suggestion
         * Setter for the AccessKey
```

2023-02-13 21:39 UTC, ksyeo1010 commented on demo/android/Activity/koala-activity-demo-app/src/androidTest/java/ai/picovoice/koalaactivitydemo/KoalaTest.java
> +    Copyright 2021 Picovoice Inc.
```suggestion
    Copyright 2023 Picovoice Inc.
```

2023-02-13 21:39 UTC, ksyeo1010 commented on demo/android/Activity/koala-activity-demo-app/src/main/java/ai/picovoice/koalaactivitydemo/MainActivity.java
> +    Copyright 2021 Picovoice Inc.
```suggestion
    Copyright 2023 Picovoice Inc.
```

2023-02-13 21:39 UTC, ksyeo1010 commented on binding/android/koala/consumer-rules.pro
> +-keep class ai.picovoice.koala.KoalaTranscript
```suggestion
```

2023-02-13 21:39 UTC, ksyeo1010 commented on binding/android/koala/proguard-rules.pro
> +-keep class ai.picovoice.koala.KoalaTranscript
```suggestion
```

2023-02-14 00:29 UTC, laves requested changes

2023-02-14 00:29 UTC, laves commented on .github/workflows/android-appcenter.yml
> +      - 'resources/test/**'
probably just want audio_samples? don't want this to run when we update our spell check

2023-02-14 00:29 UTC, laves commented on .github/workflows/android-perf.yml
> +      - 'resources/test/**'
same here, just audio_samples

2023-02-14 00:29 UTC, laves commented on README.md
> +        - [Android](#android-demos)
I think we usually put Android in front of Web

2023-02-14 00:29 UTC, laves commented on README.md
> +Replace `${ACCESS_KEY}` with yours obtained from Picovoice Console and `${MODEL_FILE}` with the default or custom trained model from [console](https://console.picovoice.ai/).
no `$MODEL_FILE` mentioned in the example

2023-02-14 00:29 UTC, laves commented on binding/android/README.md
> +Create an instance of the engine with the Koala Builder class by passing in the `accessKey`, `modelPath` and Android app context:
we're going to bundle the default model file, so we don't need the emphasis on how to include it in the docs

2023-02-14 00:29 UTC, laves commented on binding/android/README.md
> +```java
mention reset()

2023-02-14 00:29 UTC, laves commented on binding/android/README.md
> +        .setModelPath(modelPath)
I wouldn't include modelPath in the quick example. Most users will use the default model in the package, so this is a very optional option

2023-02-14 00:29 UTC, laves commented on binding/android/koala/build.gradle
> +
check out the [cobra gradle file](https://github.com/Picovoice/cobra/blob/main/binding/android/cobra/build.gradle). From now on, we're not going to commit the params or the `.so` files to the Android project. They should be copied as part of the build process and ignored.

2023-02-14 00:29 UTC, laves commented on binding/android/koala/src/main/java/ai/picovoice/koala/Koala.java
> +     * @throws KoalaException if there is an error while initializing Koala.
formatting looks off

2023-02-14 00:29 UTC, laves commented on binding/android/koala/src/main/java/ai/picovoice/koala/Koala.java
> +     * @param pcm A frame of audio samples. The number of samples per frame can be attained by
```suggestion
     * @param pcm A frame of audio samples. The number of samples per frame can be obtained by
```

2023-02-14 00:29 UTC, laves commented on binding/android/koala/src/main/java/ai/picovoice/koala/Koala.java
> +     *          time of the input frame and the start time of the output frame can be attained from {@link #delaySample()}.
```suggestion
     *          time of the input frame and the start time of the output frame can be attained from {@link #getDelaySample()}.
```

2023-02-14 00:29 UTC, laves commented on binding/android/koala/src/main/java/ai/picovoice/koala/Koala.java
> +     * @return Koala delaySample.
better to provide a short description of what the variable is rather than just reiterate the var name. More similar to sampleRate and frameLength

2023-02-14 00:29 UTC, laves commented on binding/android/koala/src/main/java/ai/picovoice/koala/KoalaNative.java
> +    static native int delaySample(long object) throws KoalaException;
getDelaySample to follow the pattern of the property getter names

2023-02-14 00:29 UTC, laves commented on binding/android/settings.gradle
> +rootProject.name = "Koala"
`libpv_koala.so` and `koala_params.pv` can be ignored and added to the gradle build. That way we don't need to remember to update them.

2023-02-14 00:29 UTC, laves commented on demo/android/Activity/README.md
> +2. Start talking. The app background will change to indicate that voice activity was detected above the threshold.
This doesn't describe the demo

2023-02-14 00:29 UTC, laves commented on demo/android/Activity/koala-activity-demo-app/src/androidTest/java/ai/picovoice/koalaactivitydemo/PerformanceTest.java
> +    public void testPerformance() throws Exception {
formatting

2023-02-14 00:29 UTC, laves commented on demo/android/README.md
> +This demo is intended for applications that need to do voice activity detection when in focus.
description from Cobra

2023-02-14 00:29 UTC, laves commented on demo/android/Activity/koala-activity-demo-app/src/main/res/layout/koala_activity_demo.xml
> +            app:layout_constraintTop_toBottomOf="@+id/faderSlider" />
Can you make this Picovoice blue?

2023-02-14 00:29 UTC, laves commented on demo/android/Activity/koala-activity-demo-app/src/main/res/layout/koala_activity_demo.xml
> +        android:text="Recorded"
Should only say `Recorded` after recording. During it should say `Recording`

2023-02-14 00:29 UTC, laves commented on demo/android/Activity/koala-activity-demo-app/src/main/res/layout/koala_activity_demo.xml
> +        android:textSize="24sp"
Might be good to use a smaller text size - there's almost no padding when the text is Record

2023-02-14 00:29 UTC, laves commented on demo/android/Activity/koala-activity-demo-app/src/main/java/ai/picovoice/koalaactivitydemo/MainActivity.java
> +                            recordedText.setText("Recorded: " + secondsRecorded + "s");
can we do a float to one decimal place for recording time? Looks more familiar as a recording timer with some milliseconds

2023-02-14 18:50 UTC, ErisMik commented on binding/android/koala/src/main/java/ai/picovoice/koala/KoalaNative.java
> +    static native int delaySample(long object) throws KoalaException;
This requires going back and updating the JNI and this part is internal and doesn't impact the public api. Alright if I make a ticket to update later and have it in for the next release instead?

2023-02-14 19:41 UTC, laves commented on binding/android/koala/src/main/java/ai/picovoice/koala/KoalaNative.java
> +    static native int delaySample(long object) throws KoalaException;
sure

2023-02-14 19:49 UTC, ErisMik commented
Markdown links failing because cocoapods.org is down right now :grimacing:

2023-02-14 19:57 UTC, ksyeo1010 approved these changes

2023-02-14 20:14 UTC, laves approved these changes

2023-02-14 20:58 UTC, merged